"""Hard gate: the Python citation-verifier port (app/services/verify.py)
must produce identical verification results to the TS original
(apps/web/lib/qa/verify.ts) on the shared fixture. If this fails, the port
has drifted from what the product actually ships client-side — fix the
port, do not adjust the fixture to match.

Fixture source of truth: apps/web/eval/verify-parity-fixture.json,
generated by apps/web/scripts/gen-verify-parity-fixture.ts by running the
real TS implementation (not hand-computed).
"""

import json
from pathlib import Path

import pytest

from app.schemas.qa import PolicyCitation
from app.services.verify import verify_citations

FIXTURE_PATH = (
    Path(__file__).resolve().parents[2]
    / "web"
    / "eval"
    / "verify-parity-fixture.json"
)


@pytest.fixture(scope="module")
def fixture():
    if not FIXTURE_PATH.exists():
        pytest.fail(
            f"Parity fixture not found at {FIXTURE_PATH}. Regenerate with "
            "`pnpm exec tsx scripts/gen-verify-parity-fixture.ts` in apps/web."
        )
    with open(FIXTURE_PATH, encoding="utf-8") as f:
        return json.load(f)


def _to_chunk(c: dict) -> PolicyCitation:
    return PolicyCitation(
        id=c["id"],
        section_label=c["sectionLabel"],
        page_start=c["pageStart"],
        page_end=c["pageEnd"],
        content=c["content"],
        similarity=c["similarity"],
    )


class TestVerifyParity:
    def test_verification_matches_ts(self, fixture):
        chunks = [_to_chunk(c) for c in fixture["chunks"]]

        for case in fixture["cases"]:
            label = case["label"]
            expected = fixture["expected"][label]
            actual = verify_citations(case["answer"], chunks)

            assert actual.verified_count == expected["verifiedCount"], label
            assert actual.total_count == expected["totalCount"], label
            assert actual.all_verified == expected["allVerified"], label
            assert len(actual.citations) == len(expected["citations"]), label

            for a, e in zip(actual.citations, expected["citations"]):
                assert a.marker == e["marker"], label
                assert a.label == e["label"], label
                assert a.pages == e["pages"], label
                assert a.status == e["status"], label
                expected_source_id = e.get("source", {}).get("id") if e.get("source") else None
                actual_source_id = a.source.id if a.source is not None else None
                assert actual_source_id == expected_source_id, label
