/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/coverage/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Coverage Analyze */
        post: operations["coverage_analyze_coverage_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qa/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Qa Answer */
        post: operations["qa_answer_qa_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qa/matter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Qa Matter */
        post: operations["qa_matter_qa_matter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CoverageAnalyzeAcceptedResponse */
        CoverageAnalyzeAcceptedResponse: {
            /**
             * Status
             * @constant
             */
            status: "accepted";
        };
        /** CoverageAnalyzeRequest */
        CoverageAnalyzeRequest: {
            /** Case Id */
            case_id: string;
            /** Claim Summary */
            claim_summary: string;
            /** Document Ids */
            document_ids: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MatterCitation */
        MatterCitation: {
            /** Content */
            content: string;
            /** Document Id */
            document_id: string;
            /** Id */
            id: number;
            /** Page End */
            page_end: number | null;
            /** Page Start */
            page_start: number | null;
            /** Section Label */
            section_label: string;
            /** Similarity */
            similarity: number;
        };
        /** PolicyCitation */
        PolicyCitation: {
            /** Content */
            content: string;
            /** Id */
            id: number;
            /** Page End */
            page_end: number | null;
            /** Page Start */
            page_start: number | null;
            /** Section Label */
            section_label: string;
            /** Similarity */
            similarity: number;
        };
        /** PolicyQAMatterRequest */
        PolicyQAMatterRequest: {
            /** Document Ids */
            document_ids: string[];
            /** Question */
            question: string;
        };
        /** PolicyQAMatterResponse */
        PolicyQAMatterResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["MatterCitation"][];
            /** Refused */
            refused: boolean;
            /** Retrieved Chunks */
            retrieved_chunks: components["schemas"]["MatterCitation"][];
            /** Top Similarity */
            top_similarity: number | null;
        };
        /** PolicyQARequest */
        PolicyQARequest: {
            /** Document Id */
            document_id: string;
            /** Question */
            question: string;
        };
        /** PolicyQAResponse */
        PolicyQAResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["PolicyCitation"][];
            /** Refused */
            refused: boolean;
            /** Retrieved Chunks */
            retrieved_chunks: components["schemas"]["PolicyCitation"][];
            /** Top Similarity */
            top_similarity: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    coverage_analyze_coverage_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoverageAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageAnalyzeAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    qa_answer_qa_answer_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyQARequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyQAResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    qa_matter_qa_matter_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyQAMatterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyQAMatterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
